<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Welcome Administrator</title>
</head>
<body>
	<h1>Revenue Generated by a Flight, Airline or Customer?</h1>
	<form action="revenueByFlight.jsp" method="get">
		<button type="submit">Revenue Generated by a Flight</button>
	</form>
	<form action="revenueByAirline.jsp" method="get">
		<button type="submit">Revenue Generated by a Airline</button>
	</form>
	<form action="revenueByCustomer.jsp" method="get">
		<button type="submit">Revenue Generated by a Customer</button>
	</form>
		<br/>
		<a href = "adminHome.jsp">Back To Dashboard</a>
</body>
</html>