<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Revenue Generated by Airline</title>
</head>
<body>
	<h2>Revenue Generated by Airline</h2>

	<form action="processRevenueByAirline.jsp" method="POST">
		Airline ID: <input type='text' name="airlineID"> <br /> <input
			type="submit" value="Generate Revenue">
	</form>
			<br/>
		<a href = "adminViewRevenue.jsp">Back To Revenue Dashboard</a>


</body>
</html>