<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Revenue Generated by Customer</title>
</head>
<body>
	<h2>Revenue Generated by Customer</h2>

	<form action="processRevenueByCustomer.jsp" method="POST">
		Account Number: <input type='text' name="accountNumber"> <br /> <input
			type="submit" value="Generate Revenue">
	</form>
				<br/>
		<a href = "adminViewRevenue.jsp">Back To Revenue Dashboard</a>


</body>
</html>