<%@ page language="java" contentType="text/html; charset=UTF-8"
	pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Revenue Generated by Flight</title>
</head>
<body>
	<h2>Revenue Generated by Flight</h2>

	<form action="processRevenueByFlight.jsp" method="POST">
		Flight Number: <input type='text' name="flightNumber"> <br /> <input
			type="submit" value="Generate Revenue">
	</form>
				<br/>
		<a href = "adminViewRevenue.jsp">Back To Revenue Dashboard</a>


</body>
</html>